export const meeting = [
  {
    id: 1,
    title: '강남 보드게임 카페에 초대합니다.',
    location: '명 보드게임카페 강남역점',
    date: '11.12',
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: '/image.png',
  },
  {
    id: 2,
    title: '강남 보드게임 카페에 초대합니다.',
    location: '명 보드게임카페 강남역점',
    date: '11.12',
    numberOfParticipants: 7,
    maximumNumber: 7,
    image: '/image.png',
  },
  {
    id: 3,
    title: '강남 보드게임 카페에 초대합니다.',
    location: '명 보드게임카페 강남역점',
    date: '11.12',
    numberOfParticipants: 1,
    maximumNumber: 6,
    image: '/image.png',
  },
  {
    id: 4,
    title: '강남 보드게임 카페에 초대합니다.',
    location: '명 보드게임카페 강남역점',
    date: '11.12',
    numberOfParticipants: 2,
    maximumNumber: 6,
    image: '/image.png',
  },
  {
    id: 5,
    title: '강남 보드게임 카페에 초대합니다.',
    location: '명 보드게임카페 강남역점',
    date: '11.12',
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: '/image.png',
  },
];
