export const meetings = [
  {
    id: '1',
    title:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '2',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 7,
    maximumNumber: 7,
    image: ['/image.png'],
  },
  {
    id: '3',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 1,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '4',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 2,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '5',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '6',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '7',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '8',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '9',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '10',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '11',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: ['/image.png'],
  },
  {
    id: '12',
    title: '강남 보드게임 카페에 초대합니다.',
    content:
      '안녕하세요 강남 보드게임방에서 같이 즐기실 분 구합니다. 게임에 대해서는 오시면 구체적으로 설명해 드릴테니 마음 편하게 오시면 될 것 같습니다.',
    location: {
      name: '다이스타운 보드게임카페',
      detail: '서울 강남구 봉은사로2길 37 3층',
      lat: 37.502166,
      lng: 127.026608,
    },
    date: '11.12 (월)',
    price: 6000,
    numberOfParticipants: 4,
    maximumNumber: 6,
    image: ['/image.png'],
  },
];
